export const GET_TODOS = 'GET_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const UPDATE_TODO =  'UPDATE_TODO'
export const UPDATE_COMPLETE_TODO = 'UPDATE_COMPLETE_TODO'
export const SEARCH_TODO = 'SEARCH_TODOS' 
